title: Mohd Farhan Ahmed # your name (or website title) here
logo: "/Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br> 
  <a href="mailto:Mohdfarhanahmed169@gmail.com">Mohdfarhanahmed169@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/mohammedfarhan-//">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
